name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  try-cmake-instal:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install libgtest-dev lcov
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ."
      - run: lcov -v 
      - run: gcov -v
      - run: mkdir build && cd build && mkdir tests && cd tests
      - run: cmake -DBUILD_CONFIGURATION=GTEST -DCMAKE_BUILD_TYPE=Debug -S ${{ github.repository }}/AoC2023 -B ${{ github.repository }}/AoC2023/build/tests -G "Unix Makefiles"
      - run: ls
      - run: make
      - run: ./AoC2023_GTest