name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  Run_GTests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install libgtest-dev lcov tree
      - run: mkdir -p build/tests 
      - run: cmake -DBUILD_CONFIGURATION=GTEST -DCMAKE_BUILD_TYPE=Debug -B build/tests -G "Unix Makefiles"
      - run: cmake --build build/tests --target AoC2023_GTest
      - run: cd build/tests 
      - run: make
      - run: ./AoC2023_GTest 
      - run: make gcov
      - run: make lcov 